---

- name: Add Zomboid server user
  ansible.builtin.user:
    name: "{{ server_user }}"
    home: "/home/{{ server_user }}"
    shell: /bin/bash
    create_home: true
    state: present

- name: Create Zomboid server directory
  ansible.builtin.file:
    path: "{{ server_game_path }}"
    state: directory
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: '0755'

- name: Install zomboid dedicated server via SteamCMD
  ansible.builtin.command: "sudo -u pzuser /usr/games/steamcmd +login anonymous +force_install_dir {{ server_game_path }} +app_update 380870 validate +quit"
  register: pz_install
  changed_when: >
    "Success! App '380870' fully installed." in pz_install.stdout

- name: Create server configuration directory
  ansible.builtin.file:
    path: "{{ server_config_path }}"
    state: directory
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: '0755'

- name: Deploy zomboid.env
  ansible.builtin.template:
    src: zomboid.env.j2
    dest: "{{ server_config_path }}/zomboid.env"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: '0644'

- name: Start Project Zomboid server
  ansible.builtin.command: "sudo -u {{ server_user }} bash -c '{{ server_game_path }}/start-server.sh -servername {{ server_name }} -adminpassword {{ server_admin_password }} <{{ server_game_path }}/zomboid.control'"
  async: 60
  poll: 0

- name: Remove Project Zomboid process if exists
  ansible.builtin.command: "killall -u {{ server_user }}"
  ignore_errors: true

# - name: Remove file if it exists
#   ansible.builtin.file:
#     path: "{{ server_game_path }}/zomboid.control"
#     state: absent

- name: Deploy server.ini
  ansible.builtin.template:
    src: server.ini.j2
    dest: "{{ server_config_path }}/{{ server_name }}.ini"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: '0644'

- name: Deploy SandboxVars.lua
  ansible.builtin.template:
    src: SandboxVars.lua.j2
    dest: "{{ server_config_path }}/{{ server_name }}_SandboxVars.lua"
    owner: "{{ server_user }}"
    group: "{{ server_user }}"
    mode: '0644'
