---

- name: Deploy Zomboid systemd service
  ansible.builtin.template:
    src: zomboid.service.j2
    dest: /etc/systemd/system/zomboid.service
    owner: root
    group: root
    mode: '0644'

- name: Deploy Zomboid socket file
  ansible.builtin.template:
    src: zomboid.socket.j2
    dest: /etc/systemd/system/zomboid.socket
    owner: root
    group: root
    mode: '0644'

- name: |
    Stop zomboid.service]
    DESCRIPTION [preventing errors if service is started and socket is not
  ansible.builtin.systemd:
    name: zomboid.service
    state: stopped
    enabled: true

- name: Enable and start PZ socket
  ansible.builtin.systemd:
    name: zomboid.socket
    state: restarted
    enabled: true
    daemon_reload: true
